questions =  [
    {"id": 0, "question": "Eta and Iota were Category 5.", "effects": {"wee": 1}},
    {"id": 1, "question": "I am educated enough to issue accurate tropical forecasts.", "effects": {"wee": -1}},
    {"id": 2, "question": "I am a tropical weenie.", "effects": {"wee": 1}},
    {"id": 3, "question": "Recon efforts should be expanded to get more accurate data.", "effects": {"inn": 1, "wee": -1}},
    {"id": 4, "question": "The NHC should work to make their forecasts more accessible.", "effects": {"inn": 1}},
    {"id": 5, "question": "NOAA and the NHC need more funding.", "effects": {"inn": 1}},
    {"id": 6, "question": "The NHC overestimates windspeeds.", "effects": {"wee": 1}},
    {"id": 7, "question": "Most NHC ratings are fair.", "effects": {"wee": -1}},
    {"id": 8, "question": "They should have kept the Greek names.", "effects": {"inn": -1, "wee": 1}},
    {"id": 9, "question": "The Emergency Alert System should be used to communicate Hurricane Watches and Warnings.", "effects": {"inn": 1}},
    {"id": 10, "question": "Most 155 mph hurricanes are just undersampled Category 5s.", "effects": {"wee": 1}},
    {"id": 11, "question": "I enjoy hurricanes as long as they don't do much damage.", "effects": {"wee": -1}},
    {"id": 12, "question": "Name retirement should be based on windspeed.", "effects": {"inn": 1}},
    {"id": 13, "question": "Hurricanes should be rated by damage rather than estimated windspeed.", "effects": {"inn": 1, "wee": 1}},
    {"id": 14, "question": "Years like 2020 will happen every year.", "effects": {"wee": 1}},
    {"id": 15, "question": "Hurricanes should start being named One, Two, etc. again.", "effects": {"inn": -1}},
    {"id": 16, "question": "People should rely on the NHC for outlooks instead of YouTube channels.", "effects": {"wee": -1}},
    {"id": 17, "question": "I know more than the NHC.", "effects": {"wee": 1}},
	{"id": 18, "question": "The criteria for Extreme Wind Warnings should be pushed down to 100 mph.", "effects": {"inn": 1}},
	{"id": 19, "question": "Raw Dvorak should be used to determine hurricane strength.", "effects": {"inn": 1, "wee": 1}},
	{"id": 20, "question": "Advanced Dvorak/ADT should be used to determine hurricane strength.", "effects": {"inn": 1, "wee": -1}},
	{"id": 21, "question": "The NHC should revert to their old outlooks.", "effects": {"wee": 1}},
	{"id": 22, "question": "There should be a Category 6 for storms above 210 mph.", "effects": {"inn": 1, "wee": 1}},
	{"id": 23, "question": "Windspeed doesn't matter, but impact does.", "effects": {"wee": -1}},
	{"id": 24, "question": "Surface observations should be used to find and determine the strength of hurricanes instead of satellites.", "effects": {"inn": -1}},
	{"id": 25, "question": "The better a storm looks, the stronger it is.", "effects": {"wee": 1}},
	{"id": 26, "question": "The NHC should forecast in all basins.", "effects": {"inn": 1}},
	{"id": 27, "question": "It is possible to see a hurricane equal to or stronger than Patricia in the Atlantic.", "effects": {"wee": 1}},
	{"id": 28, "question": "Matthew was a Category 5.", "effects": {"wee": 0.5}},
	{"id": 29, "question": "The NHC underestimates windspeeds.", "effects": {"wee": 1}},
	{"id": 30, "question": "I would be excited if a hurricane were to hit me.", "effects": {"wee": 1}},
	{"id": 31, "question": "People should be taught hurricane safety at a young age to mitigate future loss of life.", "effects": {"inn": 1, "wee": -1}},
	{"id": 32, "question": "Storms should only be tracked by the NHC if they are going to make landfall somewhere.", "effects": {"inn": -1}},
	{"id": 33, "question": "I don't think hurricanes are as impactful as people say they are.", "effects": {"wee": 1}},
	{"id": 34, "question": "I know when to and when not to joke about a hurricane and its potential impacts.", "effects": {"wee": -1}},
	{"id": 35, "question": "Invests should be warned to give people who could potentially be impacted a very early warning.", "effects": {"inn": 1}},
	{"id": 36, "question": "The Bassfield/Soso Tornado was incorrectly assessed by the NWS and should have been EF5.", "effects": {"wee": 1}},
    {"id": 37, "question": "I am educated enough to issue accurate severe forecasts.", "effects": {"wee": -1}},
    {"id": 38, "question": "I am a severe weenie.", "effects": {"wee": 1}},
    {"id": 39, "question": "March 25th and March 17th verified high risk.", "effects": {"wee": -1}},
    {"id": 40, "question": "The SPC should redesign their website.", "effects": {"inn": 1}},
    {"id": 41, "question": "The National Weather Service needs more funding.", "effects": {"inn": 1}},
    {"id": 42, "question": "April 12th, 2020 deserved to be categorized as high risk.", "effects": {"wee": 0.5}},
    {"id": 43, "question": "El Reno was EF5 strength but didn't cause EF5 damage.", "effects": {"wee": -1}},
    {"id": 44, "question": "The National Weather Service should go back to the Fujita Scale.", "effects": {"inn": -1}},
    {"id": 45, "question": "The National Weather Service shouldn't use Twitter.", "effects": {"inn": -1}},
    {"id": 46, "question": "I get mad when severe risks don't verify.", "effects": {"wee": 1}},
    {"id": 47, "question": "I believe that I have an equal skill level to severe experts.", "effects": {"wee": 1}},
    {"id": 48, "question": "60 significant hail should be modified to high risk.", "effects": {"inn": 1}},
    {"id": 49, "question": "April 27th, 2011 was the worst tornado outbreak in modern times.", "effects": {"inn": 1, "wee": -1}},
    {"id": 50, "question": "I would be excited if a tornado hit me.", "effects": {"wee": 1}},
    {"id": 51, "question": "The SPC should get rid of Marginal and Enhanced risks because they can be confusing.", "effects": {"inn": -1}},
    {"id": 52, "question": "PDS watches should be phased out to avoid confusion.", "effects": {"inn": -1}},
    {"id": 53, "question": "Doppler radar/DOW estimated windspeeds should be used to rate tornadoes.", "effects": {"inn": 1, "wee": 1}},
	{"id": 54, "question": "I like it when tornadoes hit populated areas.", "effects": {"inn": -1}},
	{"id": 55, "question": "Rochelle was an EF5, not an EF4.", "effects": {"inn": 0.5}},
	{"id": 56, "question": "I believe the NWS unfairly rates tornadoes.", "effects": {"wee": 1}},
	{"id": 57, "question": "I try to warn people in the path of a tornado in any way I can.", "effects": {"wee": -1}},
	{"id": 58, "question": "The NWS should work on upgrading their radars to issue warnings more efficiently.", "effects": {"inn": 1, "wee": -1}},
	{"id": 59, "question": "I like to overhype severe events.", "effects": {"wee": -1}},
	{"id": 60, "question": "Tornadoes should be rated on strength instead of damage.", "effects": {"inn": 0.5, "wee": 1}},
	{"id": 61, "question": "I wish years like 2011 happened every year.", "effects": {"wee": 1}},
	{"id": 62, "question": "Tornado warnings shouldn't be issued for rural areas because it is a waste of resources.", "effects": {"inn": -1}},
	{"id": 63, "question": "I enjoy tornadoes as long as they don't do much damage.", "effects": {"wee": -1}},
	{"id": 64, "question": "I would be excited if I were in a high risk.", "effects": {"wee": 1}},
	{"id": 65, "question": "Tornado watches should be issued days in advance similar to hurricane watches.", "effects": {"inn": 1}},
	{"id": 66, "question": "The bigger a tornado, the stronger it is, and the smaller a tornado, the weaker it is.", "effects": {"wee": 1}},
	{"id": 67, "question": "I do not think tornadoes are a major hazard.", "effects": {"wee": 1}},
	{"id": 68, "question": "I want an EF5 to happen very soon.", "effects": {"wee": 1}},
	{"id": 69, "question": "The NWS should use the TORRO scale.", "effects": {"inn": -1}},
	{"id": 70, "question": "I wish the severe weather season lasted yearround.", "effects": {"wee": 1}},
	{"id": 71, "question": "Models should be improved to provide more accurate forecasts further in advance.", "effects": {"inn": 1, "wee": -1}}
];
